apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-chart.fullname" . }}
  labels:
    {{- include "postgres-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: postgres
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database | quote }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ include "postgres-chart.fullname" . }}-pvc
      {{- else }}
      - name: postgres-data
        emptyDir: {}
      {{- end }}

